[package]
name = "git-warp-time"
version = "0.2.1"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2018"
description = "Rust library and CLI utility to reset file timestamps to repo state"
homepage = "https://github.com/alerque/git-warp-time"
repository = "https://github.com/alerque/git-warp-time"
license = "GPL-3.0-only"

[[bin]]
name = "git-warp-time"
build = "build.rs"

[dependencies]
filetime = "0.2.14"

  [dependencies.clap]
  version = "3.0.0-beta.2"
  features = [ "wrap_help" ]

  [dependencies.git2]
  version = "0.13.17"
  default-features = false

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"

  [build-dependencies.vergen]
  version = "5.0.1"
  default-features = false
  features = [ "build", "git" ]

[profile.release]
lto = true
