[package]
name = "git-warp-time"
version = "0.4.3"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2018"
description = "Rust library and CLI utility to reset file timestamps to repo state"
readme = "README.md"
homepage = "https://github.com/alerque/git-warp-time"
repository = "https://github.com/alerque/git-warp-time"
license = "GPL-3.0-only"
build = "build.rs"
include = ["*.rs"]

[[bin]]
name = "git-warp-time"
required-features = ["cli"]

[dependencies]
filetime = "0.2.14"

  [dependencies.clap]
  version = "3.0.0-beta.2"
  optional = true
  features = [ "wrap_help" ]

  [dependencies.git2]
  version = "0.13.17"
  default-features = false

[build-dependencies]
clap = { version = "3.0.0-beta.2", optional = true }
clap_generate = { version = "3.0.0-beta.2", optional = true }

  [build-dependencies.vergen]
  version = "5.0.1"
  default-features = false
  features = [ "build", "git" ]

[features]
default = ["cli", "bash", "elvish", "fish", "powershell", "zsh"]
completions = ["cli", "clap_generate"]
cli = ["clap"]
bash = ["completions"]
elvish = ["completions"]
fish = ["completions"]
powershell = ["completions"]
zsh = ["completions"]

[profile.release]
lto = true
