[package]
name = "git-time-warp"
version = "0.0.0"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
