[package]
name = "git-warp-time"
version = "0.4.5"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2021"
description = "Rust library and CLI utility to reset file timestamps to repo state"
readme = "README.md"
homepage = "https://github.com/alerque/git-warp-time"
repository = "https://github.com/alerque/git-warp-time"
license = "GPL-3.0-only"
build = "build.rs"
include = ["*.rs"]

[[bin]]
name = "git-warp-time"
required-features = ["cli"]

[dependencies]
filetime = "0.2.19"

  [dependencies.clap]
  version = "4.0.30"
  optional = true
  features = [ "derive", "wrap_help" ]

  [dependencies.git2]
  version = "0.15.0"
  default-features = false

[build-dependencies]
clap_complete = { version = "4.0.6", optional = true }

  [build-dependencies.clap]
  version = "4.0.30"
  optional = true
  features = [ "derive" ]

  [build-dependencies.vergen]
  version = "7.4.3"
  default-features = false
  features = [ "build", "git" ]

[patch.crates-io.vergen]
git = "https://github.com/alerque/vergen"
branch = "bump-libgit2"

[features]
default = ["cli", "bash", "elvish", "fish", "powershell", "zsh"]
completions = ["cli", "clap_complete"]
cli = ["clap"]
bash = ["completions"]
elvish = ["completions"]
fish = ["completions"]
powershell = ["completions"]
zsh = ["completions"]

[profile.release]
lto = true
