name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:

  ghrelase:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "${GITHUB_REF#refs/*/v}" > .tarball-version
          ./bootstrap.sh
          ./configure --without-{bash,fish,zsh}-completion-dir --disable-dependency-checks
      - name: Build source package
        run: |
          make dist
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            git-warp-time-${{ env.VERSION }}.zip
            git-warp-time-${{ env.VERSION }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.token }}
